# Generated by Django 4.2 on 2023-11-24 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doors', '0002_historicaldoor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='door',
            name='inside_img',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inside_panel', to='doors.panel', verbose_name='Внутреняя панель'),
        ),
        migrations.AlterField(
            model_name='door',
            name='outside_img',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outside_panel', to='doors.panel', verbose_name='Внешняя панель'),
        ),
    ]
